# Generated by Django 5.2.7 on 2025-11-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date_start',
            field=models.DateField(),
        ),
    ]
