# Generated by Django 5.2.7 on 2025-11-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_hotel_id_reservations_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='date of creation'),
        ),
    ]
